### ISSUE TITLE
BUG:文件频繁打开没被复用

### ISSUE THREAD

**Issue by insionng** [tango-contrib/tpongo2#2]
{"err":"[Error (where: fromfile) in templates/index.html] open templates/index.html: too many open files"}

**Comment by lunny** [comment]
可能没有吧。我没用，所以没关注。

**Comment by insionng** [comment]
reload选项打开了之后出现的,估计是没考虑到这情况吧?

**Comment by lunny** [comment]
有可能。

**Comment by lunny** [comment]
这个不是问题啊。Reload打开就是每次都重新打开啊。

**Comment by insionng** [comment]
好吧 关闭问题~
