### ISSUE TITLE
在os x 10.10.5下，压测会报错

### ISSUE THREAD

**Issue by LYY** [tango-contrib/tpongo2#3]
系统：Mac OS X 10.10.5
go版本： 1.4.2
tango版本：master
tpongo2版本：master

压测工具:  [wrk](https://github.com/wg/wrk)
错误日志：[gist:13d1a7657227743f7ce4](https://gist.github.com/LYY/13d1a7657227743f7ce4)
测试代码：[LYY/gotestlab/tangolab](https://github.com/LYY/gotestlab/tree/master/tangolab)

测试命令：`wrk -t5 -c10 -d30s http://localhost:8001/pongo`

**Comment by lunny** [comment]
Hi, I have tested via [boom](https://github.com/rakyll/boom). And not found the error.
My test command is `boom -n=1000 -c=10 -t=5000 http://localhost:8001/pongo`.

Please ensure your dependency package is the latest. And test it again.
My Go version is 1.5

**Comment by lunny** [comment]
Below is the additional code based on your test codes.
```Go
func InitUsers() map[string]string {
	return map[string]string{
		"name": "value",
		"xlw": "ttt",
	}
}
```

**Comment by LYY** [comment]
I got dependency packages yesterday, so I think it would be the latest. The function `InitUsers` is here: [labcomm](https://github.com/LYY/gotestlab/tree/master/labcomm).

I rebuilded my test and run it again, the error was still there, and the error always `Handler crashed with error: error on writing template: n(3965) != buffer.Len(238039)`

**Comment by lunny** [comment]
I have found the reason because tpongo2 use `gopkg.in/flosch/pongo2.v3` but echo's ponger use `github.com/flosch/pongo2`. And when I use `github.com/flosch/pongo2`, It's OK. So I will change the reference to `github.com/flosch/pongo2`. @flosch
